version: '2.1'

services:
  rabbitmq:
    image: io.huta/rabbitmq:3.8.2
    ports:
      - "8501:15672"
      - "5671:5671"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    cpu_shares: 102
    mem_limit: 512m
    healthcheck:
      test: ["CMD-SHELL","rabbitmqctl status | grep pid"]
      interval: 15s
      timeout: 5s
      retries: 10